server:
  port: 8888
logging:
  level:
    ROOT: INFO

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/carnellj/config-repo.git
          searchPaths: licensingservice, organizationservice
          username: native-cloud-apps
          password: Offended