server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/jonathandavis/IdeaProjects/configurationserver/src/main/resources/config/licensingservice